#!/bin/bash

DUR_POMODORO=25
INTERVALO_CURTO=5
INTERVALO_LONGO=15
AGUARDA_RESPOSTA=2m #aqui usa o sleep simples, então simplifica usando minutos mesmo
TAMANHO_JANELA=150
NOME="POMODORO"
CAMINHO_SOM_POMODORI=/usr/share/sounds/freedesktop/stereo/message-new-instant.oga
CAMINHO_SOM_POMODORO=/usr/share/sounds/freedesktop/stereo/complete.oga
CAMINHO_SOM_INTERVALO=/usr/share/sounds/freedesktop/stereo/suspend-error.oga 

ativa_timer_notifica() {
	aguarda=$(($3 * 60 / 100))
	timer $aguarda $1 $2
	zenity --title=$NOME --notification --text="Acabou o $1 $2"
	paplay $4 
}

pomodori() {
	for pom in {1..4}
	do
		valida_continuacao "pomodoro" $pom $DUR_POMODORO $CAMINHO_SOM_POMODORO

		if [ $pom -lt 4 ]
		then
			valida_continuacao "intervalo"  $pom $INTERVALO_CURTO $CAMINHO_SOM_INTERVALO
		else
			valida_continuacao "intervalo" $pom $INTERVALO_LONGO $CAMINHO_SOM_INTERVALO
		fi
	done
}

timer() {
	for ((i=0;i<=100;i+=1))
	do
		echo "$i"
		sleep $1
	done | zenity --progress --title=$NOME --text="$2 $3" --percentage="0" --auto-close --auto-kill
}

valida_continuacao() {
	if pergunta $1 $2
	then
		ativa_timer_notifica $1 $2 $3 $4
	fi
}

pergunta() {
	if zenity --question --title=$NOME --width=$TAMANHO_JANELA --text="Você deseja ir para $1 $2?"
	then
		return 0
	fi

	sleep $AGUARDA_RESPOSTA
	pergunta $1 $2
}

main() {
	pomodori_atual=1
	total_pomodoris=$(zenity --entry --title=$NOME --width=$TAMANHO_JANELA --text="Quantos pomodori você quer?")

	while [ $pomodori_atual -le $total_pomodoris ]
	do
		zenity --title=$NOME --notification --text="Iniciando o pomodori $pomodori_atual"
		paplay $CAMINHO_SOM_POMODORI 

		pomodori

		pomodori_atual=$(( $pomodori_atual + 1 ))
	done
}

main

